### ISSUE TITLE
Update Blender plugin to Blender 2.8

### ISSUE THREAD

**Issue by SirDifferential** [Delicode/NI-mate-plugins#5]
Once the Blender 2.8 Python changes are set in stone, go through the plugin and make it work with the new Blender version. We'll have to host two versions from then on, keeping the old version available for users of Blender < 2.8

Links:

https://en.blender.org/index.php/Dev:2.8/
https://en.blender.org/index.php/Dev:2.8/Source/Migration#Python_API
https://en.blender.org/index.php/Dev:2.8/Source/Python/UpdatingScripts
https://en.blender.org/index.php/Dev:2.8/Source/LayersCollections/API-Changes

**Comment by kaezone** [comment]
For reference: if anyone wants to try out Blender 2.8 with NImate while it's in beta, you'll need to change the Blender version in bl_info to `(2,80,0)`, and register the following classes as https://en.blender.org/index.php/Dev:2.8/Source/Python/UpdatingScripts says.
```
classes = (
    DelicodeNImateFeedPlaneCreate,
    DelicodeNImateFeedLogicCreate,
    DelicodeNImateReceiverLogicCreate,
    DelicodeNImate,
    DelicodeNImateStop,
    VIEW3D_PT_DelicodeNImatePanel
)
```
The game engine was removed in 2.8, so `VIEW3D_PT_DelicodeNImateGEPanel` will cause problems. Additionally, `empty_draw_size` needs to be changed to `empty_display_size`.

**Comment by plachenko** [comment]
Hey I added a pull request that allows you to use ni-mate with 2.8 for now. It should work well with blender 2.80.53 if anyone wants to use ni-mate now. Just enable the plugin and look to the right hand menu (not the left hand menu). I took the game engine features out since the game engine is deprecated and I'm not sure those features would work past 2.8. I'd love to get the camera feed into eevee though!
